name: flutter_web_xr
description: Plugin for creating Augmented Reality experiences for Flutter Web.
version: 0.0.2
repository: https://github.com/Felix2019/flutter-web-ar-plugin
issue_tracker: https://github.com/Felix2019/flutter-web-ar-plugin/issues
topics:
  - augmented-reality
  - flutter-web
  - webxr

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.7
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # This section identifies this Flutter project as a plugin project.
  plugin:
    platforms:
      web:
        pluginClass: FlutterWebXrWeb
        fileName: flutter_web_xr_web.dart